pipeline {
    agent any
     environment {
        NODE_ENV = 'test'
        VERCEL_TOKEN = credentials('VERCEL_TOKEN')
    }
   
    stages {
        
        stage('Build') {
            agent {
                docker {
                    image 'node:22.11.0-alpine3.20'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    npm install
                    npm run build
                    ls -l
                '''
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'node:22.11.0-alpine3.20'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    npm run test
                '''
            }
        }
        stage('deploy'){
            agent {
                docker {
                    image 'node:22.11.0-alpine3.20'
                    args '-u root'
                    reuseNode true
                }
            }
            steps{
                sh '''
                npm install -g vercel
                vercel --prod --token=$VERCEL_TOKEN --confirm --name=cicdproject
                '''
            }
    
        }
    }
}
